Fix compilation: missing typedef for uint32_t
status.cc:12:3: error: ‘uint32_t’ was not declared in this scope

Change-Id: Id6ea656937f8db39976603a504bcdd0c7559e488
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@digia.com>